# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/5fd09f31-e069-4c9f-84d9-4ebc01d2d220";
    fsType = "btrfs";
    options = ["subvol=@home"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/5fd09f31-e069-4c9f-84d9-4ebc01d2d220";
    fsType = "btrfs";
    options = ["subvol=@nix"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/B3D1-FFAE";
    fsType = "vfat";
  };
  fileSystems."/mnt/data" = {
    device = "/dev/disk/by-uuid/a345152a-f9b6-44bd-9e5a-65dcb324378d";
    fsType = "btrfs";
    options = ["compress=zstd"];
  };
  fileSystems."/mnt/media" = {
    device = "/dev/disk/by-uuid/cca14173-924a-4de2-9f12-793aa3ee49fa";
    fsType = "btrfs";
    options = ["compress=zstd"];
  };
  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
